-- ============================================
-- NYC Taxi Analytics — Snowflake Setup Script
-- Run this once in a Snowflake Worksheet
-- ============================================

-- Step 1: Create database
CREATE DATABASE IF NOT EXISTS NYC_TAXI;

-- Step 2: Create schemas
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.RAW;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.STAGING;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.ANALYTICS;

-- Step 3: Create warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  COMMENT = 'Warehouse for NYC Taxi Analytics project';

-- Step 4: Create role for dbt
CREATE ROLE IF NOT EXISTS TRANSFORMER;

-- Step 5: Grant permissions
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORMER;
GRANT ALL ON DATABASE NYC_TAXI TO ROLE TRANSFORMER;
GRANT ALL ON ALL SCHEMAS IN DATABASE NYC_TAXI TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE NYC_TAXI TO ROLE TRANSFORMER;
GRANT ALL ON ALL TABLES IN DATABASE NYC_TAXI TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN DATABASE NYC_TAXI TO ROLE TRANSFORMER;

-- Step 6: Assign role to your user
-- ⚠️  Replace YOUR_USERNAME with your actual Snowflake username
GRANT ROLE TRANSFORMER TO USER YOUR_USERNAME;
